# Generated by Django 6.0.4 on 2026-05-04 03:52

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footageupload',
            name='footage_file',
            field=models.FileField(upload_to=uploads.models.footage_upload_path),
        ),
    ]
