# Generated by Django 6.0.4 on 2026-05-04 03:57

import django.db.models.deletion
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_footageupload_footage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footageupload',
            name='footage_file',
        ),
        migrations.CreateModel(
            name='FootageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footage_file', models.FileField(upload_to=uploads.models.footage_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footage_files', to='uploads.footageupload')),
            ],
        ),
    ]
