# Generated by Django 6.0.4 on 2026-05-04 04:03

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_remove_footageupload_footage_file_footagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footageupload',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='footageupload',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='footageupload',
            name='footage_file',
            field=models.FileField(blank=True, null=True, upload_to=uploads.models.footage_upload_path),
        ),
        migrations.DeleteModel(
            name='FootageFile',
        ),
    ]
