# Generated by Django 6.0.4 on 2026-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_footageupload_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footageupload',
            name='project_name',
            field=models.CharField(max_length=150),
        ),
    ]
